### ISSUE TITLE
Не авторизует

### ISSUE THREAD

**Issue by stripwire** [iiiypuk/vk0nline#1]
Токен вставил, но авторизация не проходит. Нужно ли заполнять остальные поля конфига? И чем их заполнять?

**Comment by iiiypuk** [comment]
Да, нужно заполнять.
clientId это legacy))
secureKey и serviceKey это параметры приложения.

**Comment by stripwire** [comment]
И откуда всё это взять?

**Comment by iiiypuk** [comment]
{
      "clientId": 0,
      "secureKey": "0bW9blZFX05qAQtANuqc",
      "serviceKey": "b35beffdb35beffdb35beffdb1b331f335bb35bb35beffdefe06c4ddace5d1feae74669",
      "accessToken": ""
    }
На
